version: '3.1'
services:
  db:
    image: mysql:5.6
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: MashaMasha/07041998
      MYSQL_DATABASE: allnews
      MYSQL_PASSWORD: MashaMasha/07041998
  app:
    build: . 
    restart: unless-stopped
    ports:
      - 8085:8085
      - 3000:3000
    links:
      - db